### ISSUE TITLE
"cluster addon list" segfaults

### ISSUE THREAD

**Issue by tpo** [xetys/hetzner-kube#146]
How to reproduce:

1. local machine is Debian stretch, Intel Laptop
2. wget https://github.com/xetys/hetzner-kube/releases/download/0.3/hetzner-kube
3. chmod +x hetzner-kube
3. ./hetzner-kube help # works
4. ./hetzner-kube cluster addon list

```
me@here:~$ ./hetzner-kube.0.3 cluster addon list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x81bbb2]

goroutine 1 [running]:
github.com/xetys/hetzner-kube/cmd.glob..func8(0xb96d20, 0xbbc140, 0x0, 0x0)
        /home/david/go/src/github.com/xetys/hetzner-kube/cmd/cluster_addon_list.go:38 +0x1e2
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).execute(0xb96d20, 0xbbc140, 0x0, 0x0, 0xb96d20, 0xbbc140)
        /home/david/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb988c0, 0xc42014a7e1, 0x0, 0x0)
        /home/david/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra.(*Command).Execute(0xb988c0, 0x91b970, 0x5)
        /home/david/go/src/github.com/xetys/hetzner-kube/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/xetys/hetzner-kube/cmd.Execute()
        /home/david/go/src/github.com/xetys/hetzner-kube/cmd/root.go:51 +0x82
main.main()
        /home/david/go/src/github.com/xetys/hetzner-kube/main.go:20 +0x20
```

what am I missing?

**Comment by tpo** [comment]
Thanks @JohnnyQQQQ

**Comment by jcassee** [comment]
@JohnnyQQQQ I'm still seeing this panic in version 0.3.2-rc1, is that expected?

**Comment by kunthar** [comment]
0.5.1 and still there. 
```
./hetzner-kube-0.5.1-darwin-amd64  version
0.5.1
```
```
$./hetzner-kube-0.5.1-darwin-amd64  cluster addon list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x149fd0d]

goroutine 1 [running]:
github.com/xetys/hetzner-kube/cmd.glob..func8(0x1a04300, 0x1a2cf90, 0x0, 0x0)
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/cmd/cluster_addon_list.go:25 +0x1cd
github.com/spf13/cobra.(*Command).execute(0x1a04300, 0x1a2cf90, 0x0, 0x0, 0x1a04300, 0x1a2cf90)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1a034c0, 0x15c6b58, 0x5, 0xc000048700)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/xetys/hetzner-kube/cmd.Execute()
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/cmd/root.go:37 +0x86
main.main()
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/main.go:6 +0x20
```
