### ISSUE TITLE
bug: cluster create should not encounter panic

### ISSUE THREAD

**Issue by rockymadden** [xetys/hetzner-kube#147]
I am attempting to create a basic cluster from the readme and I am met each time with the below error. 

## Details
* Compiling via `go get -u github.com/xetys/hetzner-kube`.
* Tried against `0.3` tag with same outcome.
* Go reports version as `go version go1.10.3 darwin/amd64`

## Debug
```console
$ hetzner-kube cluster create --name cluster --ssh-key ssh                                                                          
2018/06/14 21:16:42 Creating new cluster

NAME:cluster
MASTERS: 1
WORKERS: 1
ETCD NODES: 3
HA: false
ISOLATED ETCD: false
2018/06/14 21:16:43 creating server 'cluster-master-01'...
  --- [======================================] 100%
2018/06/14 21:17:08 Created node 'cluster-master-01' with IP 78.47.241.117
2018/06/14 21:17:08 creating server 'cluster-worker-01'...
  --- [======================================] 100%
2018/06/14 21:17:30 Created node 'cluster-worker-01' with IP 78.47.240.34
2018/06/14 21:17:30 sleep for 10s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x128d13b]

goroutine 217 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.(*SSHCommunicator).RunCmd(0xc4201b2a00, 0xc420390800, 0x11, 0x14fdb62, 0x4, 0x0, 0xc4202877e0, 0xc, 0xc420287800, 0x9, ...)
	/Users/rockymadden/.go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/ssh_communicator.go:45 +0xbb
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).packagesAreInstalled(0xc4205c76a8, 0xc420390800, 0x11, 0x14fdb62, 0x4, 0x0, 0xc4202877e0, 0xc, 0xc420287800, 0x9, ...)
	/Users/rockymadden/.go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:58 +0x91
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).Provision(0xc42005fea8, 0xc420390800, 0x11, 0x14fdb62, 0x4, 0x0, 0xc4202877e0, 0xc, 0xc420287800, 0x9, ...)
	/Users/rockymadden/.go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:37 +0xca
github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes.func1(0xc4203edc00, 0xc4203f15c0, 0xc4203f1620, 0xc420390800, 0x11, 0x14fdb62, 0x4, 0x0, 0xc4202877e0, 0xc, ...)
	/Users/rockymadden/.go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:85 +0x1b8
created by github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes
	/Users/rockymadden/.go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:81 +0x17d
```

**Comment by JohnnyQQQQ** [comment]
It's also showing 3 etcd nodes but none will be created as etcd is not isolated and ha is false. I will investigate this weekend.

**Comment by rockymadden** [comment]
@JohnnyQQQQ Nice, thanks!

**Comment by felixfischer** [comment]
Similar here, so I subscribe to this thread.

Details:

* go version go1.10.3 darwin/amd64
* Compiled via `go get -u github.com/xetys/hetzner-kube`

```
hetzner-kube cluster create --name nh --ssh-key 'Felix Fischer (rsa)'
2018/06/15 20:21:36 Creating new cluster

NAME:nh
MASTERS: 1
WORKERS: 1
ETCD NODES: 3
HA: false
ISOLATED ETCD: false
2018/06/15 20:21:36 creating server 'nh-master-01'...
  --- [======================================] 100%
2018/06/15 20:22:01 Created node 'nh-master-01' with IP 159.69.49.26
2018/06/15 20:22:01 creating server 'nh-worker-01'...
  --- [======================================] 100%
2018/06/15 20:22:28 Created node 'nh-worker-01' with IP 159.69.49.27
2018/06/15 20:22:28 sleep for 10s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1290a38]

goroutine 315 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.(*SSHCommunicator).RunCmd(0xc4201869e0, 0xc420304260, 0xc, 0x1519527, 0x4, 0x101, 0xc4202beec4, 0xc, 0xc4202beee0, 0x8, ...)
	/Users/felix/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/ssh_communicator.go:45 +0xd8
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).packagesAreInstalled(0xc420059ea8, 0xc420304260, 0xc, 0x1519527, 0x4, 0x101, 0xc4202beec4, 0xc, 0xc4202beee0, 0x8, ...)
	/Users/felix/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:58 +0x91
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).Provision(0xc42054dea8, 0xc420304260, 0xc, 0x1519527, 0x4, 0x101, 0xc4202beec4, 0xc, 0xc4202beee0, 0x8, ...)
	/Users/felix/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:37 +0xca
github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes.func1(0xc4205a8000, 0xc42007fc20, 0xc42007fc80, 0xc420304260, 0xc, 0x1519527, 0x4, 0x101, 0xc4202beec4, 0xc, ...)
	/Users/felix/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:85 +0x1b8
created by github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes
	/Users/felix/go/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:81 +0x17d
```

**Comment by JohnnyQQQQ** [comment]
I can't reproduce the problem with the current master branch.

**Comment by xetys** [comment]
Maybe this is a Mac related issue? As I'm not a Mac user I can't test that

**Comment by rockymadden** [comment]
Perhaps, I can try testing that.

**Comment by rockymadden** [comment]
Closed in favor of a different solution.

**Comment by sergolius** [comment]
Got this error.
Env: MacOS Mojave, version 10.14.1
Used release: hetzner-kube-0.3.2-rc1-darwin-amd64

### Debug:
```
hetzner-kube cluster create --name k8s --ssh-key k8s --master-count 1 --worker-count 1 --datacenters nbg1-dc3
2018/12/06 16:38:17 Creating new cluster

NAME:k8s
MASTERS: 1
WORKERS: 1
ETCD NODES: 0
HA: false
ISOLATED ETCD: false
2018/12/06 16:38:17 creating server 'k8s-master-01'...
  --- [======================================] 100%
2018/12/06 16:38:21 Created node 'k8s-master-01' with IP 116.203.26.161
2018/12/06 16:38:21 creating server 'k8s-worker-01'...
  --- [======================================] 100%
2018/12/06 16:38:25 Created node 'k8s-worker-01' with IP 116.203.30.136
2018/12/06 16:38:25 sleep for 10s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x128d33b]

goroutine 101 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.(*SSHCommunicator).RunCmd(0xc420188c80, 0xc42058ac50, 0xd, 0x151ad6a, 0x4, 0x0, 0xc420442460, 0xe, 0xc420442490, 0x9, ...)
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/pkg/clustermanager/ssh_communicator.go:45 +0xbb
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).packagesAreInstalled(0xc4204c96a8, 0xc42058ac50, 0xd, 0x151ad6a, 0x4, 0x0, 0xc420442460, 0xe, 0xc420442490, 0x9, ...)
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:58 +0x91
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).Provision(0xc420263ea8, 0xc42058ac50, 0xd, 0x151ad6a, 0x4, 0x0, 0xc420442460, 0xe, 0xc420442490, 0x9, ...)
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:37 +0xca
github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes.func1(0xc4200c9800, 0xc420098a20, 0xc420098a80, 0xc42058ac50, 0xd, 0x151ad6a, 0x4, 0x0, 0xc420442460, 0xe, ...)
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:85 +0x1b8
created by github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes
	/home/travis/gopath/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:81 +0x17d
```

**Comment by mavimo** [comment]
@sergolius take a look to https://github.com/xetys/hetzner-kube/issues/180

**Comment by sergolius** [comment]
@mavimo thanks, just viewed it
