### ISSUE TITLE
segfault during cluster creation

### ISSUE THREAD

**Issue by MartinNowak** [xetys/hetzner-kube#192]
```shell
$ uname -a
Linux FedoraX64 4.17.18-200.fc28.x86_64 #1 SMP Wed Aug 22 19:08:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ hetzner-kube version
0.3.1-RELEASE
$ hetzner-kube cluster create --ssh-key mykey --name test
2018/10/02 22:24:20 Creating new cluster

NAME:t8s
MASTERS: 1
WORKERS: 1
ETCD NODES: 0
HA: false
ISOLATED ETCD: false
2018/10/02 22:24:20 creating server 't8s-master-01'...
  --- [======================================] 100%
2018/10/02 22:24:42 Created node 't8s-master-01' with IP 78.46.xxx.xxx
2018/10/02 22:24:42 creating server 't8s-worker-01'...
  --- [======================================] 100%
2018/10/02 22:25:05 Created node 't8s-worker-01' with IP 78.46.xxx.xxx
2018/10/02 22:25:05 sleep for 10s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x687978]

goroutine 335 [running]:
github.com/xetys/hetzner-kube/pkg/clustermanager.(*SSHCommunicator).RunCmd(0xc42016c920, 0xc420384db0, 0xd, 0x9194a7, 0x4, 0x0, 0xc42034a0e0, 0xd, 0xc42034a100, 0x9, ...)
	/home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/ssh_communicator.go:45 +0xd8
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).packagesAreInstalled(0xc4204e3ea8, 0xc420384db0, 0xd, 0x9194a7, 0x4, 0x0, 0xc42034a0e0, 0xd, 0xc42034a100, 0x9, ...)
	/home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:58 +0x91
github.com/xetys/hetzner-kube/pkg/clustermanager.(*NodeProvisioner).Provision(0xc420187ea8, 0xc420384db0, 0xd, 0x9194a7, 0x4, 0x0, 0xc42034a0e0, 0xd, 0xc42034a100, 0x9, ...)
	/home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/provision_node.go:37 +0xca
github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes.func1(0xc4204f5700, 0xc42007f560, 0xc42007f5c0, 0xc420384db0, 0xd, 0x9194a7, 0x4, 0x0, 0xc42034a0e0, 0xd, ...)
	/home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:85 +0x1b8
created by github.com/xetys/hetzner-kube/pkg/clustermanager.(*Manager).ProvisionNodes
	/home/david/go-path/src/github.com/xetys/hetzner-kube/pkg/clustermanager/cluster.go:81 +0x17d
```

**Comment by tobias-reese** [comment]
Seems to be a duplicate of #180. Please close this.
